### ISSUE TITLE
[FEATURE REQUEST] Allow Recursive Association

### ISSUE THREAD

**Issue by go4cas** [Agontuk/schema-designer#6]
It would be really great if one could define recursive associations, i.e. a foreign key on the same table:

Example: `category` table:
Columns:
```
- id (primary key)
- title
- parent_id (foreign key)
```
where `parent_id` would reference `id`

**Comment by go4cas** [comment]
I have managed to get this going, by manually editing the exported .json file, and re-importing:
![recursive](https://user-images.githubusercontent.com/12674784/40822085-bc877f00-656a-11e8-99b1-7672893134d4.png)

**Comment by Agontuk** [comment]
Thanks, I'll take a look.

**Comment by Agontuk** [comment]
Site has been updated with recursive association support, sorry for the long delay.
